// METADATA
export const SITE_TITLE = 'Scissors'
export const SITE_DESCRIPTION =
  'Your awesome application for versatile image formatting and processing!'
export const SITE_KEYWORDS = [
  'image',
  'processing',
  'photo',
  'filter',
  'picture',
  'color correction',
  'cropping',
  'mask',
  'trimming',
  'brightness',
  'contrast',
  'saturation',
  'shadow',
  'lighting',
  'effect',
  'collage',
  'noise',
  'blur',
  'sharpness',
  'chroma',
  'retro',
  'composition',
  'vignette',
  'pixelation',
  'conversion',
  'resizing',
  'quality',
  'rotation',
  'format',
  'compress',
  'crop',
  'jpeg',
  'jpg',
  'png',
  'webp',
  'avif',
  'tiff',
  'scissors'
] as const
