export const TOUR_LS_KEY = 'scissors-tour-completed'
export const TOUR_STEP = {
  FILE_UPLOAD: 1,
  TOOLBAR_TAB_LIST: 2,
  TOOLBAR_ACTIONS: 3,
  SETTINGS_PANEL: 4,
  REQUEST_BUTTON: 5,
  DOWNLOAD_BUTTON: 6,
  DOCUMENTATION_LINK: 7
} as const
export const MIN_STEP_TO_SKIP = TOUR_STEP.REQUEST_BUTTON
