import {
  EXTEND_DIRECTION_SIZE_STEP,
  MAX_EXTEND_DIRECTION_SIZE,
  MIN_EXTEND_DIRECTION_SIZE
} from '@scissors/sharp'

export const DEFAULT_EXTEND_INPUT_PROPS = {
  min: MIN_EXTEND_DIRECTION_SIZE,
  max: MAX_EXTEND_DIRECTION_SIZE,
  step: EXTEND_DIRECTION_SIZE_STEP
} as const
