name: Frontend e2e testing

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.14.0

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
          browser: chrome
